language: node_js
node_js:
- '11.0'
branches:
  only:
  - master
cache:
  directories:
  - "./node_modules"
before_script:
- npm install -g @angular/cli
script:
- npm install
- ng build --aot --prod
deploy:
  skip_cleanup: true
  provider: heroku
  api-key:
    secure: ''
  api_key:
    secure: orUNyyu5QveBB9syXsjJH9xwwgylL4asg5yIYJHWcykyYndHWPXdKw7Ka2ZK01s4hGCu1tA2jA+S5bHsEsNsAveKuoVmkbK24HlOi0NniizubBEDOmcSNBeJpgyqFNK8fN5aFzE+FFdDh2XJ/wOJME7qmxiZR64yKNhUJVQOxmImKTcB/NHAtWuXRt+F5yScEhFTeaS4iTWsmS8eG9gE7MN4ntAiIoRoRmIKv7vmBrG2U3EKqUKN0FSQiACHzlFxylKiqZ2BNOYkyeEHCmC53+tp2E534vIXEYy4BhNcHPf71Ca/xb7AuNcVqEExvsoj5mIDiSlgnVlJGoRf5S4m5Oj7cblPjrRLnz6VCyEY/mH47cx70P6D+dpUjWXcklMm+pnDNH6wtdQYvebEDWdtUbmGrzDmBCQf3v6Xl6h+nkzy611n9bNAitgIHCwMM2P+wEz73+3Q4N2KV53GSrwU/3bKADIUGOacj92aGGelqjpkPKvM1CXJMtP9osUVwYD8U0BzaKOuPAsUqIPaGPlXqVXv8+3QwGhFLEDeJh9REA/sAoF8VBkTMVNA99oNFoIDYgfAQG+B4sICnkWN3cTAp1J4xFDso7CO16/1VXErsvPaa5bBbkb1ctUgwn6027LZb5LvzQb7PgzCYxHzNFDf1o/K7KhRB17avZO7Rwo/oa0=
